name: Unit tests

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node: ["14", "16"]

        steps:
            - name: Git checkout
              uses: actions/checkout@v2

            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  cache: "npm"
                  node-version: ${{ matrix.node }}

            - name: Install dependencies
              run: npm install

            - name: Run tests
              run: npm test
